### ISSUE TITLE
IIS is not configured to point to default.aspx

### ISSUE THREAD

**Issue by AndrewBrianHall** [justcla/ASPNet-VM#3]
For Web Forms apps, IIS is not configured to route to default.aspx if no location is specific in the URL.  We should update the template to add that to IIS as well

**Comment by shirhatti** [comment]
I don't believe that's the case. Once you've enabled ASP.NET, here's what the default document section looks like in your applicationHost.config

```xml
        <defaultDocument enabled="true">
            <files>
                <add value="Default.htm" />
                <add value="Default.asp" />
                <add value="index.htm" />
                <add value="index.html" />
                <add value="iisstart.htm" />
                <add value="default.aspx" />
            </files>
        </defaultDocument>
```

It already has an entry for *default.aspx*.

**Comment by AndrewBrianHall** [comment]
It's not working that way, here was my scenario:

- Use Justin's template to create a VM and then add DNS to it
- Publish a Web Forms app from Visual Studio
- VS pops the browser to the root URL for the VM, I get the IIS page, not the default.aspx page

**Comment by shirhatti** [comment]
Ahh. I know what's happening. Default publish through VS enables the [DoNotDeleteRule](https://technet.microsoft.com/en-us/library/dd568992(v=ws.10).aspx) in WebDeploy which doesn't delete the iisstart.htm page at the destination.

I think the better solution is to nuke out the contents of the inetpub/wwwroot folder as part of the custom script
